name: eb_hy
description: EasyBeach project for hy
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_svg: ^1.0.0
  google_fonts: ^4.0.4
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.8
  flutter_tts: ^3.8.5
  just_audio: ^0.9.33
  elevenlabs_flutter: ^0.0.1
  audioplayers: ^5.2.1
  path_provider: ^2.1.2

  intl: ^0.17.0
  flutter:
    sdk: flutter
  video_player: ^2.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  document_file_save_plus: ^2.0.0
  solana_web3: ^0.1.3
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/logo.svg
    - assets/svg/avator1.svg
    - assets/svg/avator2.svg
    - assets/svg/avator3.svg
    - assets/svg/bg_home.svg
    - assets/svg/cashback.svg
    - assets/svg/receive.svg
    - assets/svg/send.svg
    - assets/svg/scan.svg
    - assets/svg/cross.svg
    - assets/svg/cloud.svg
    - assets/svg/electricity.svg
    - assets/svg/filter.svg
    - assets/svg/flight.svg
    - assets/svg/logout.svg
    - assets/svg/movie.svg
    - assets/svg/menu.svg
    - assets/svg/babysitting.svg
    - assets/svg/more.svg
    - assets/svg/logo.png
    - assets/svg/logo2.png
    - assets/svg/home_main_talk.png
    - assets/svg/home_uni_grad_image.png
    - assets/svg/like_icon.png
    - assets/svg/like_icon_2.svg
    - assets/svg/share_icon.png
    - assets/svg/taik_logo.png
    - assets/svg/uni_logo_stories.png
    - assets/svg/profile_avatar.png
    - assets/svg/for_image_1.png
    - assets/svg/for_you_image_2.png
    - assets/svg/for_you_image_3.png
    - assets/svg/gigs_icon.png
    - assets/svg/search_icon.png
    - assets/svg/taik_logo.webp
    - assets/svg/like.webp
    - assets/svg/share.webp
    - assets/svg/for_you_3.webp
    - assets/svg/for_you_amazon.webp
    - assets/svg/for_you_grad.webp
    - assets/svg/cadbury_logo.webp
    - assets/svg/expedia_logo.webp
    - assets/svg/lego_logo.webp
    - assets/svg/LV_logo.webp
    - assets/svg/monzo_logo.webp
    - assets/svg/solana_logo.webp
    - assets/svg/microphone.webp
    - assets/svg/student_support_service_profile_image.webp
    - assets/svg/student_support_service_profile_image_2.webp
    - assets/svg/edit_bot_info.webp
    - assets/svg/1UP_AR.webp
    - assets/svg/1UP_incoming_messages.webp
    - assets/svg/1UP_search.webp
    - assets/svg/1UP_shop.webp
    - assets/svg/1UP_token.webp
    - assets/svg/1UP_gigs.webp
    - assets/svg/1UP_logo.png
    - assets/svg/nike_logo.webp
    - assets/svg/action_button_1.webp
    - assets/svg/action_button_2.webp
    - assets/svg/action_button_3.webp
    - assets/svg/action_button_4.webp
    - assets/svg/short_1.png
    - assets/svg/short_2.png
    - assets/svg/short_3.png
    - assets/svg/social_feed_talk_ai.webp
    - assets/svg/feed_like.webp
    - assets/svg/feed_comment.webp
    - assets/svg/feed_share.webp
    - assets/svg/post_image_profile.png
    - assets/svg/heart_like.png
    - assets/svg/1-UP_logo_signin.png
    - assets/svg/solana_main.webp
    - assets/svg/AR.mp4
    - assets/svg/lego.png
    - assets/svg/model.png
    - assets/svg/model2.png
    - assets/svg/model3.png
    - assets/svg/tutor.png
    - assets/svg/tutor2.png
    - assets/svg/tutor3.png
    - assets/svg/celeb.png
    - assets/svg/celeb2.png
    - assets/svg/celeb3.png
    - assets/svg/video1.mp4
    - assets/svg/video2.mp4
    - assets/svg/video3.mp4
    - assets/svg/video4.mp4
    - assets/svg/professor_animated_1.mp4
    - assets/svg/professor_animated_2.mp4

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
